#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.2 on Sun Nov 27 19:30:43 2016
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
'''
La classe de l’application a pour nom :
MainCourante_Fenetre
'''
'''
A copier dans MainCourante_Fenetre.__init__()
        self.list_ctrl_ListeVictime = wx.ListCtrl(self, -1 , style=wx.LC_REPORT)
        self.list_ctrl_ListeVictime.InsertColumn(0, 'HH', width=30)
        self.list_ctrl_ListeVictime.InsertColumn(1, 'MM', width=30)
        self.list_ctrl_ListeVictime.InsertColumn(2, 'Nom', width=100)
        self.list_ctrl_ListeVictime.InsertColumn(3, 'Prenom', width=100)
        self.list_ctrl_ListeVictime.InsertColumn(4, 'Circonstances', width=200)
        self.list_ctrl_ListeVictime.InsertColumn(5, 'HH', width=30)
        self.list_ctrl_ListeVictime.InsertColumn(6, 'MM', width=30)
'''
# end wxGlade


class MainCourante_Fenetre(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainCourante_Fenetre.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.list_ctrl_ListeVictime = wx.ListCtrl(self, wx.ID_ANY)
        self.button_Editer_Raffraichir = wx.Button(self, wx.ID_ANY, _("Rafraichir"))
        self.spin_ctrl_1 = wx.SpinCtrl(self, wx.ID_ANY, "", min=0, max=100)
        self.button_Editer = wx.Button(self, wx.ID_ANY, _("Editer"))
        self.button_Effacer = wx.Button(self, wx.ID_ANY, _("Effacer"))
        self.button_Nouvelle = wx.Button(self, wx.ID_ANY, _("Nouvelle"))
        self.button_Enregistrer = wx.Button(self, wx.ID_ANY, _("Enregistrer"))
        self.button_Ouvrir = wx.Button(self, wx.ID_ANY, _("Ouvrir"))

        self.list_ctrl_ListeVictime = wx.ListCtrl(self, -1 , style=wx.LC_REPORT)
        self.list_ctrl_ListeVictime.InsertColumn(0, 'HH', width=30)
        self.list_ctrl_ListeVictime.InsertColumn(1, 'MM', width=30)
        self.list_ctrl_ListeVictime.InsertColumn(2, 'Nom', width=100)
        self.list_ctrl_ListeVictime.InsertColumn(3, 'Prenom', width=100)
        self.list_ctrl_ListeVictime.InsertColumn(4, 'Circonstances', width=300)
        self.list_ctrl_ListeVictime.InsertColumn(5, 'HH', width=30)
        self.list_ctrl_ListeVictime.InsertColumn(6, 'MM', width=30)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.Selection_Ligne, self.list_ctrl_ListeVictime)
        self.Bind(wx.EVT_BUTTON, self.Raffraichir, self.button_Editer_Raffraichir)
        self.Bind(wx.EVT_BUTTON, self.Editer, self.button_Editer)
        self.Bind(wx.EVT_BUTTON, self.Effacer, self.button_Effacer)
        self.Bind(wx.EVT_BUTTON, self.Nouvelle, self.button_Nouvelle)
        self.Bind(wx.EVT_BUTTON, self.Enregistrer, self.button_Enregistrer)
        self.Bind(wx.EVT_BUTTON, self.Ouvrir, self.button_Ouvrir)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainCourante_Fenetre.__set_properties
        self.SetTitle(_("Main Courante CRF65"))
        self.list_ctrl_ListeVictime.SetMinSize((600, 350))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainCourante_Fenetre.__do_layout
        sizer_Fenetre = wx.BoxSizer(wx.VERTICAL)
        sizer_CadreFenetre = wx.BoxSizer(wx.VERTICAL)
        sizer_CadreBoutons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_MainCourante = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, _("MAIN COURANTE")), wx.HORIZONTAL)
        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, _("VICTIMES")), wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_Cadre_Raffraichir = wx.BoxSizer(wx.HORIZONTAL)
        sizer_CadreFenetre.Add(self.list_ctrl_ListeVictime, 1, wx.EXPAND, 0)
        sizer_Cadre_Raffraichir.Add(self.button_Editer_Raffraichir, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_CadreFenetre.Add(sizer_Cadre_Raffraichir, 0, 0, 0)
        sizer_3.Add(self.spin_ctrl_1, 0, 0, 0)
        sizer_3.Add(self.button_Editer, 0, 0, 0)
        sizer_3.Add(self.button_Effacer, 0, 0, 0)
        sizer_2.Add(sizer_3, 1, 0, 0)
        sizer_2.Add(self.button_Nouvelle, 0, 0, 0)
        sizer_CadreBoutons.Add(sizer_2, 1, 0, 0)
        sizer_MainCourante.Add(self.button_Enregistrer, 0, 0, 0)
        sizer_MainCourante.Add(self.button_Ouvrir, 0, 0, 0)
        sizer_CadreBoutons.Add(sizer_MainCourante, 1, 0, 0)
        sizer_CadreFenetre.Add(sizer_CadreBoutons, 0, 0, 0)
        sizer_Fenetre.Add(sizer_CadreFenetre, 1, wx.ALIGN_CENTER | wx.EXPAND, 0)
        self.SetSizer(sizer_Fenetre)
        sizer_Fenetre.Fit(self)
        self.Layout()
        # end wxGlade

    def Selection_Ligne(self, event):  # wxGlade: MainCourante_Fenetre.<event_handler>
        print "Event handler 'Selection_Ligne' not implemented!"
        event.Skip()

    def Raffraichir(self, event):  # wxGlade: MainCourante_Fenetre.<event_handler>
        print "Event handler 'Raffraichir' not implemented!"
        event.Skip()

    def Editer(self, event):  # wxGlade: MainCourante_Fenetre.<event_handler>
        print "Event handler 'Editer' not implemented!"
        event.Skip()

    def Effacer(self, event):  # wxGlade: MainCourante_Fenetre.<event_handler>
        print "Event handler 'Effacer' not implemented!"
        event.Skip()

    def Nouvelle(self, event):  # wxGlade: MainCourante_Fenetre.<event_handler>
        print "Event handler 'Nouvelle' not implemented!"
        event.Skip()

    def Enregistrer(self, event):  # wxGlade: MainCourante_Fenetre.<event_handler>
        print "Event handler 'Enregistrer' not implemented!"
        event.Skip()

    def Ouvrir(self, event):  # wxGlade: MainCourante_Fenetre.<event_handler>
        print "Event handler 'Ouvrir' not implemented!"
        event.Skip()

# end of class MainCourante_Fenetre
